# Dataframe

##  iloc

In [56]:
import pandas as pd
import random
 
# read the data from the downloaded CSV file.
data = pd.read_csv('https://s3-eu-west-1.amazonaws.com/shanebucket/downloads/uk-500.csv')
# set a numeric id for use as an index for examples.
data['id'] = [random.randint(0,1000) for x in range(data.shape[0])]
 
data.head(2)

first_name   last_name             company_name       address  \
0    Aleshia  Tomkiewicz  Alan D Rosenburg Cpa Pc  14 Taylor St   
1       Evan   Zigomalas       Cap Gemini America   5 Binney St   

                city           county    postal        phone1        phone2  \
0  St. Stephens Ward             Kent   CT2 7PP  01835-703597  01944-369967   
1         Abbey Ward  Buckinghamshire  HP11 2AX  01937-864715  01714-737668   

                      email                                   web   id  
0   atomkiewicz@hotmail.com  http://www.alandrosenburgcpapc.co.uk  331  
1  evan.zigomalas@gmail.com     http://www.capgeminiamerica.co.uk  922

In [57]:
# Single selections using iloc and DataFrame
# Rows:
data.iloc[0] # first row of data frame (Aleshia Tomkiewicz) - Note a Series data type output.
data.iloc[1] # second row of data frame (Evan Zigomalas)
data.iloc[-1] # last row of data frame (Mi Richan)
# Columns:
data.iloc[:,0] # first column of data frame (first_name)
data.iloc[:,1] # second column of data frame (last_name)
data.iloc[:,-1] # last column of data frame (id)
print()

## loc and set_index

In [58]:
data.set_index("last_name", inplace=True)
data.head(2)

first_name             company_name       address  \
last_name                                                      
Tomkiewicz    Aleshia  Alan D Rosenburg Cpa Pc  14 Taylor St   
Zigomalas        Evan       Cap Gemini America   5 Binney St   

                         city           county    postal        phone1  \
last_name                                                                
Tomkiewicz  St. Stephens Ward             Kent   CT2 7PP  01835-703597   
Zigomalas          Abbey Ward  Buckinghamshire  HP11 2AX  01937-864715   

                  phone2                     email  \
last_name                                            
Tomkiewicz  01944-369967   atomkiewicz@hotmail.com   
Zigomalas   01714-737668  evan.zigomalas@gmail.com   

                                             web   id  
last_name                                              
Tomkiewicz  http://www.alandrosenburgcpapc.co.uk  331  
Zigomalas      http://www.capgeminiamerica.co.uk  922

In [59]:
data.loc['Zigomalas']

first_name                                   Evan
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
id                                            922
Name: Zigomalas, dtype: object

In [60]:
data.loc[['Tomkiewicz', 'Zigomalas']]

first_name             company_name       address  \
last_name                                                      
Tomkiewicz    Aleshia  Alan D Rosenburg Cpa Pc  14 Taylor St   
Zigomalas        Evan       Cap Gemini America   5 Binney St   

                         city           county    postal        phone1  \
last_name                                                                
Tomkiewicz  St. Stephens Ward             Kent   CT2 7PP  01835-703597   
Zigomalas          Abbey Ward  Buckinghamshire  HP11 2AX  01937-864715   

                  phone2                     email  \
last_name                                            
Tomkiewicz  01944-369967   atomkiewicz@hotmail.com   
Zigomalas   01714-737668  evan.zigomalas@gmail.com   

                                             web   id  
last_name                                              
Tomkiewicz  http://www.alandrosenburgcpapc.co.uk  331  
Zigomalas      http://www.capgeminiamerica.co.uk  922

In [61]:
data.loc[['Tomkiewicz', 'Zigomalas'], ['first_name', 'address', 'city']]

first_name       address               city
last_name                                             
Tomkiewicz    Aleshia  14 Taylor St  St. Stephens Ward
Zigomalas        Evan   5 Binney St         Abbey Ward

In [62]:
# Select rows with index values 'Andrade' and 'Veness', with all columns between 'city' and 'email'
data.loc[['Andrade', 'Veness'], 'city':'email']
# Select same rows, with just 'first_name', 'address' and 'city' columns
data.loc['Andrade':'Veness', ['first_name', 'address', 'city']]


first_name            address                            city
last_name                                                              
Andrade       France       8 Moor Place  East Southbourne and Tuckton W
Mcwalters    Ulysses      505 Exeter Rd              Hawerby cum Beesby
Veness        Tyisha  5396 Forth Street      Greets Green and Lyng Ward

In [63]:
# Change the index to be based on the 'id' column
data.set_index('id', inplace=True)

first_name             company_name       address               city  \
id                                                                         
331    Aleshia  Alan D Rosenburg Cpa Pc  14 Taylor St  St. Stephens Ward   
922       Evan       Cap Gemini America   5 Binney St         Abbey Ward   

              county    postal        phone1        phone2  \
id                                                           
331             Kent   CT2 7PP  01835-703597  01944-369967   
922  Buckinghamshire  HP11 2AX  01937-864715  01714-737668   

                        email                                   web  
id                                                                   
331   atomkiewicz@hotmail.com  http://www.alandrosenburgcpapc.co.uk  
922  evan.zigomalas@gmail.com     http://www.capgeminiamerica.co.uk

In [73]:
data.head(5)

first_name             company_name            address  \
id                                                           
331    Aleshia  Alan D Rosenburg Cpa Pc       14 Taylor St   
922       Evan       Cap Gemini America        5 Binney St   
291     France      Elliott, John W Esq       8 Moor Place   
168    Ulysses           Mcmahan, Ben L      505 Exeter Rd   
360     Tyisha           Champagne Room  5396 Forth Street   

                               city           county    postal        phone1  \
id                                                                             
331               St. Stephens Ward             Kent   CT2 7PP  01835-703597   
922                      Abbey Ward  Buckinghamshire  HP11 2AX  01937-864715   
291  East Southbourne and Tuckton W      Bournemouth   BH6 3BE  01347-368222   
168              Hawerby cum Beesby     Lincolnshire  DN36 5RP  01912-771311   
360      Greets Green and Lyng Ward    West Midlands   B70 9DT  01547-429341   

           phone2                       email  \
id                                              
331  01944-369967     atomkiewicz@hotmail.com   
922  01714-737668    evan.zigomalas@gmail.com   
291  01935-821636  france.andrade@hotmail.com   
168  01302-601380         ulysses@hotmail.com   
360  01290-367248   tyisha.veness@hotmail.com   

                                      web  
id                                         
331  http://www.alandrosenburgcpapc.co.uk  
922     http://www.capgeminiamerica.co.uk  
291      http://www.elliottjohnwesq.co.uk  
168          http://www.mcmahanbenl.co.uk  
360        http://www.champagneroom.co.uk

In [74]:
data.loc[922]

first_name                                   Evan
company_name                   Cap Gemini America
address                               5 Binney St
city                                   Abbey Ward
county                            Buckinghamshire
postal                                   HP11 2AX
phone1                               01937-864715
phone2                               01714-737668
email                    evan.zigomalas@gmail.com
web             http://www.capgeminiamerica.co.uk
Name: 922, dtype: object

## loc with boolean

In [66]:
data.loc[data['first_name'] == 'Aleshia']

first_name             company_name       address               city  \
id                                                                         
331    Aleshia  Alan D Rosenburg Cpa Pc  14 Taylor St  St. Stephens Ward   

    county   postal        phone1        phone2                    email  \
id                                                                         
331   Kent  CT2 7PP  01835-703597  01944-369967  atomkiewicz@hotmail.com   

                                      web  
id                                         
331  http://www.alandrosenburgcpapc.co.uk

In [67]:
data.loc[data['first_name'] == 'Aleshia', ['first_name', 'address', 'city']]

first_name       address               city
id                                             
331    Aleshia  14 Taylor St  St. Stephens Ward

In [68]:
data.loc[data['first_name'] == 'Aleshia', 'email']
# returns a Series

id
331    atomkiewicz@hotmail.com
Name: email, dtype: object

In [69]:
data.loc[data['first_name'] == 'Aleshia', ['email']]
# returns a Dataframe

email
id                          
331  atomkiewicz@hotmail.com

In [83]:
data.reset_index(inplace=True)
data.head(3)

index   id first_name             company_name       address  \
0      0  331    Aleshia  Alan D Rosenburg Cpa Pc  14 Taylor St   
1      1  922       Evan       Cap Gemini America   5 Binney St   
2      2  291     France      Elliott, John W Esq  8 Moor Place   

                             city           county    postal        phone1  \
0               St. Stephens Ward             Kent   CT2 7PP  01835-703597   
1                      Abbey Ward  Buckinghamshire  HP11 2AX  01937-864715   
2  East Southbourne and Tuckton W      Bournemouth   BH6 3BE  01347-368222   

         phone2                       email  \
0  01944-369967     atomkiewicz@hotmail.com   
1  01714-737668    evan.zigomalas@gmail.com   
2  01935-821636  france.andrade@hotmail.com   

                                    web  
0  http://www.alandrosenburgcpapc.co.uk  
1     http://www.capgeminiamerica.co.uk  
2      http://www.elliottjohnwesq.co.uk

In [84]:
# Select rows with first name Antonio, # and all columns between 'city' and 'email'
data.loc[data['first_name'] == 'Antonio', 'city':'email']
 
# Select rows where the email column ends with 'hotmail.com', include all columns
data.loc[data['email'].str.endswith("hotmail.com")]   
 
# Select rows with last_name equal to some values, all columns
data.loc[data['first_name'].isin(['France', 'Tyisha', 'Eric'])]   
       
# Select rows with first name Antonio AND hotmail email addresses
data.loc[data['email'].str.endswith("gmail.com") & (data['first_name'] == 'Antonio')] 
 

# A lambda function that yields True/False values can also be used.
# Select rows where the company name has 4 words in it.
data.loc[data['company_name'].apply(lambda x: len(x.split(' ')) == 4)] 
 
# Selections can be achieved outside of the main .loc for clarity:
# Form a separate variable with your selections:
idx = data['company_name'].apply(lambda x: len(x.split(' ')) == 4)
# Select only the True values in 'idx' and only the 3 columns specified:
data.loc[idx, ['email', 'first_name', 'company']]
print()

In [86]:
# select rows with id column between 100 and 200, and just return 'postal' and 'web' columns
data.loc[(data['id'] > 100) & (data['id'] <= 400), ['postal', 'web']] 
print()



https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.reset_index.html

## Dataframe from dict

In [1]:
import pandas

d = {'col1': 2, 'col2': 2.5}
df = pandas.DataFrame(data=d, index=[0])

print(df['col2'])
print(df.col2)

0    2.5
Name: col2, dtype: float64
0    2.5
Name: col2, dtype: float64


In [8]:
import pandas
import matplotlib.pyplot as plt
import numpy as np

# Read in dataset
iris = pandas.read_csv("data/iris.csv")

In [15]:

# shuffle rows
shuffled_rows = np.random.permutation(iris.index)
iris = iris.loc[shuffled_rows,:]
# iris.iloc[shuffled_rows]
print(iris.head())

    sepal_length  sepal_width  petal_length  petal_width          species
51           5.8          2.7           5.1          1.9   Iris-virginica
33           6.0          2.7           5.1          1.6  Iris-versicolor
89           6.9          3.1           5.4          2.1   Iris-virginica
76           6.2          2.8           4.8          1.8   Iris-virginica
85           7.7          3.0           6.1          2.3   Iris-virginica


In [12]:

# There are 2 species
print(iris.species.unique())

['Iris-virginica' 'Iris-versicolor']


## loc vs array notation

dfmi['one'] selects the first level of the columns and returns a DataFrame that is singly-indexed. Then another python operation dfmi_with_one['second'] selects the series indexed by 'second' happens. This is indicated by the variable dfmi_with_one because pandas sees these operations as separate events. e.g. separate calls to __getitem__, so it has to treat them as linear operations, they happen one after another.

Contrast this to df.loc[:,('one','second')] which passes a nested tuple of (slice(None),('one','second')) to a single call to __getitem__. This allows pandas to deal with this as a single entity. Furthermore this order of operations can be significantly **faster**, and allows one to index both axes if so desired.

# np.numpy.column_stack newaxis and reshape

To transpose or reshape a (n,) shape array, you need to use np.newaxis.

In [5]:
y = np.array([1,2,3,4])
z = np.array([2,2,2,2])
y*z
print(y.shape)
d = np.transpose(y)
d.shape

(4,)


(4,)

In [6]:
y = y[:, np.newaxis]
z = z[:, np.newaxis]

In [7]:
y*z

array([[2],
       [4],
       [6],
       [8]])

In [2]:
import numpy as np
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [36]:
import numpy as np
x = np.array([[1],[2]])
y =  np.array([1,2])
y

array([1, 2])

In [37]:
z = y[:,np.newaxis]
z

array([[1],
       [2]])

In [44]:
# the previous statement is the same as y.reshape
z = y.reshape(2, 1)
z

array([[1],
       [2]])

In [47]:
l = z[np.newaxis,:]
l

array([[[1],
        [2]]])

In [45]:
print('we can now compute x * z')
print(x*z)

we can now compute x * z
[[1]
 [4]]


In [40]:
z = z.reshape(2,)
z

array([1, 2])

In [41]:
# if you specify a parameter for the column you end with a 2 dim array
w = z.reshape(1,2)
w

array([[1, 2]])

## center

In [37]:
str = "this is string example....wow!!!"
print("str.center(40, 'a') : ", str.center(40, 'a'))

str.center(40, 'a') :  aaaathis is string example....wow!!!aaaa


## textwrap

In [1]:
import textwrap
s = "This is a very very very very very long string."
w = 4
print(textwrap.fill(s,w))
print(textwrap.wrap(s,w))

This
is a
very
very
very
very
very
long
stri
ng.
['This', 'is a', 'very', 'very', 'very', 'very', 'very', 'long', 'stri', 'ng.']


In [35]:
def wrap(string, max_width):
    return textwrap.fill(string, max_width)
string, max_width = input(), int(input())
print(wrap(string, max_width))

asdlkasjdLAKDJ
2
as
dl
ka
sj
dL
AK
DJ


## Set

In [ ]:
a, b=[set(input().split()) for i in range(2)]
print(len(a ^ b))

* Test a is a strict superset of all other input sets

In [ ]:
a = set(input().split())
print(all(a > set(input().split()) for _ in range(int(input()))))

## Sorted

In [48]:

# set
pySet = {'e', 'a', 'u', 'o', 'i'}
print(sorted(pySet, reverse=True))

['u', 'o', 'i', 'e', 'a']


### Sort can be based on a function

In [65]:
# dictionary sorted from keys
pyDict = {'e': 1, 'a': 2, 'u': 3, 'o': 4, 'i': 5}
list_items = sorted(pyDict.items(), key = lambda x: x[0] )
list_items

[('a', 2), ('e', 1), ('i', 5), ('o', 4), ('u', 3)]

In [66]:
# dictionary sorted from values
pyDict = {'e': 1, 'a': 2, 'u': 3, 'o': 4, 'i': 5}
list_tup = sorted(pyDict.items(), key = lambda x: x[1] )
list_tup

[('e', 1), ('a', 2), ('u', 3), ('o', 4), ('i', 5)]

In [67]:
# dictionary sorted first from values then from keys if values are the same
pyDict = {'e': 1, 'a': 2, 'u': 3, 'b': 1, 'i': 5}
list_items = sorted(pyDict.items(), key = lambda x: (x[1], x[0]) )
list_items

[('b', 1), ('e', 1), ('a', 2), ('u', 3), ('i', 5)]

In [68]:
# dictionary sorted first from descending values then from keys if values are the same
pyDict = {'e': 1, 'a': 2, 'u': 3, 'b': 1, 'i': 5}
list_items = sorted(pyDict.items(), key = lambda x: (-x[1], x[0]) )
list_items

[('i', 5), ('u', 3), ('a', 2), ('b', 1), ('e', 1)]

## Reverse sorted list

In [69]:
my_list = ['hello', 'abracadabra', 'hi']
sorted(my_list, key = len, reverse = True)

['abracadabra', 'hello', 'hi']

## Dictionary

### From a list of tuples

In [71]:
list_tup = [('e', 1), ('a', 2), ('u', 3), ('o', 4), ('i', 5)]
dict(list_tup)

{'a': 2, 'e': 1, 'i': 5, 'o': 4, 'u': 3}

### from a list of keys and a list of values

In [75]:
keys = ['a', 'b', 'c']
values = [3, 5, 1]
dict(zip(keys, values))

{'a': 3, 'b': 5, 'c': 1}

## Itertools groupby

# The collections Package

## Counter

In [32]:
from collections import Counter


s = 'aaahhhjjjkskkkkklllbbb'
c = Counter(s)
print(c)

Counter({'k': 6, 'a': 3, 'h': 3, 'j': 3, 'l': 3, 'b': 3, 's': 1})


### Counter.most_common() 

In [76]:
from collections import Counter
Counter('abracadabra').most_common(3)
[('a', 5), ('r', 2), ('b', 2)]

[('a', 5), ('r', 2), ('b', 2)]

In [84]:
import re
words = re.findall(r'\w+', open('data/hamlet.txt').read().lower())
Counter(words).most_common(10)
# [('the', 1143), ('and', 966), ('to', 762), ('of', 669), ('i', 631),
# ('you', 554),  ('a', 546), ('my', 514), ('hamlet', 471), ('in', 451)]

[('the', 1091),
 ('and', 969),
 ('to', 767),
 ('of', 675),
 ('i', 633),
 ('a', 571),
 ('you', 558),
 ('my', 520),
 ('in', 451),
 ('it', 421)]


#### Warning! 

works differently in Python 2 and Python 3.

1) In Python 3, if multiple elements have the same count, a random subset will be returned, in a random order.

2) In Python 2, if multiple elements have the same count, the set will be ordered, top N elements will be returned, but in a random order. You will always get "a,b,c" from the alphabet, but you might get "b,a,c" or "c,a,b",etc. Not so in Python 3.

As an example: Imagine you want to print the three more commun letters in a string. If 2 or more letters appear the same amount of times in the string, you want them to be ordered alphabetically: You cannot use the most_common() method to pick up the most common letters alphabetically ordered() from a string as you will get a wrong result with Python3:

In [77]:
from collections import Counter

s = 'aaahhhjjjkskkkkklllbbb'
c = Counter(s)
c.most_common(3)

[('k', 6), ('a', 3), ('h', 3)]

We want 'b' to be printed instead of 'h'. You can get this right using:

In [49]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [81]:
# sorted(iterable, function)
# Sort items from the dictionary c (c.items() return a list of tuples: (dict_key, dict_value)), 
# sort is based on descending values (-x[1]) and if values are the same for items
# sort is based on the dict keys (x[0]). 
sort_list = sorted(c.items(), key=lambda x: (-x[1], x[0]))
sort_list[:3]

[('k', 6), ('a', 3), ('b', 3)]

Finf out the only number that is not repeated.

Sample Input

1 2 3 6 5 4 4 2 5 3 6 1 6 5 3 2 4 1 2 5 1 4 3 6 8 4 3 1 5 6 2 

Sample Output

8
(the only number that is not repeated)

In [ ]:
from collections import Counter

c = Counter(input().split())
print(int(c.most_common()[-1][0]))


In [ ]:
from collections import Counter 
 
a = map(int, input().split())  
nums = Counter(a)  
print(min(nums, key=nums.get))


## OrderedDict keeps the insertion order in the dict:

In [4]:
from collections import Counter, OrderedDict
class OrderedCounter(Counter, OrderedDict):
    pass
d = OrderedCounter(input() for _ in range(int(input())))
print(len(d))
print(*d.values())

3
pebble
fish
fish
2
1 2


## deque

collections.deque()

A deque is a double-ended queue. It can be used to add or remove elements from both ends.

Deques support thread safe, memory efficient appends and pops from either side of the deque with approximately the same performance in either direction.

Sample Input

* 6
* append 1
* append 2
* append 3
* appendleft 4
* pop
* popleft

Sample Output

1 2

In [ ]:
from collections import deque
d = deque()
for _ in range(int(input())):
    cmd, *arg = input().split()
    getattr(d, cmd)(*arg)
print(*d)

There is a horizontal row of cubes. The length of each cube is given. You need to create a new vertical pile of cubes.

When stacking the cubes, you can only pick up either the leftmost or the rightmost cube each time. Print "Yes" if it is possible to stack the cubes. Otherwise, print "No". 

Sample Input

2
6
4 3 2 1 3 4
3
1 3 2

Sample Output

Yes
No


In [ ]:
from collections import deque
nb_d = int(input())
for _ in range(nb_d):
    n, deq = int(input()), deque(input().split())

    for cube in reversed(sorted(deq)):
   
        if cube == deq[0]:
            deq.popleft()
        elif cube == deq[-1]:
            deq.pop()
        else:
            print('No')
            break
    else:
        print("Yes")

## Convert a tuple to a string

In [92]:
tup = (1, 2, 5, 4, 3)
tup = tuple(map(str, tup))
string = " ".join(tup)
string

'1 2 5 4 3'

## Display a tuple

In [88]:
tup = (1, 2, 5, 4, 3)
print(*tup, sep=";")

1;2;5;4;3


In [89]:
tup = [('k', 6), ('a', 3), ('b', 3)]
# iterate over the 3 first tuples from sort_list:
for tup in sort_list[:3]:
    # tup = tuple(map(str, tup))
    # print(" ".join(tup))
    print(*tup)

k 6
a 3
b 3


## Generator

In [38]:
element = (1, 1, 2, 3)
print(" ".join(str(e) for e in element))

1 1 2 3


## How to replace characters in a string using a dictionary (keys standing for chars and values for replacement

In [11]:
# Create a dictionary from 2 lists (keys and values)
dict2 = dict(zip(list('hlo'),list('pwu')))
table = str.maketrans(dict2)
'123hello.jpg'.translate(table)

'123pewwu.jpg'

In [10]:
# Create a dictionary from keys with None value. 
table = str.maketrans(dict.fromkeys('0123456789'))
# Replace the specified char with "" (None)
'123hello.jpg'.translate(table)

'hello.jpg'

### More details

In [5]:
# Building a dictionary with the fromkeys method:
dict.fromkeys('0123456789')

{'0': None,
 '1': None,
 '2': None,
 '3': None,
 '4': None,
 '5': None,
 '6': None,
 '7': None,
 '8': None,
 '9': None}

In [19]:
# Translating keys to unicode numbers
str.maketrans(dict.fromkeys('0123456789'))

{48: None,
 49: None,
 50: None,
 51: None,
 52: None,
 53: None,
 54: None,
 55: None,
 56: None,
 57: None}

In [13]:
str.maketrans(dict2)

{104: 'p', 108: 'w', 111: 'u'}

# Regexp

## Search



In [4]:
import re
year_strings = []
strings = ['War of 1812', 'There are 5280 feet to a mile', 'Happy New Year 2016!']
for string in strings:
    new = re.search("[1-2][0-9]{3}", string)
    if new is not None:
        year_strings.append(string)
year_strings


['War of 1812', 'Happy New Year 2016!']

Search for tags in posts and count them: [Serious], (Serious),[serious] or (serious). We assume that there is up to one tag in each string.

In [7]:
import re
posts = [['What\'s your internet "white whale", something you\'ve been searching for years to find with no luck?', '11510', '1433213314.0', '1', '26195'], ["What's your favorite video that is 10 seconds or less?", '8656', '1434205517.0', '4', '8479'], ['What are some interesting tests you can take to find out about yourself?', '8480', '1443409636.0', '1', '4055'], ["PhD's of Reddit. What is a dumbed down summary of your thesis?", '7927', '1440188623.0', '0', '13201'], ['What is cool to be good at, yet uncool to be REALLY good at?', '7711', '1440082910.0', '0', '20325'], ['[Serious] Redditors currently in a relationship, besides dinner and a movie, what are your favorite activities for date night?', '7598', '1439993280.0', '2', '5389'],  ["Parents of Reddit, what's something that your kid has done that you pretended to be angry about but secretly impressed or amused you?", '7553', '1439161809.0', '0', '11520'], ['What is a good subreddit to binge read the All Time Top Posts of?', '7498', '1438822288.0', '0', '2780'], ['What would the person who named Walkie Talkies have named other items?', '7501', '1447904351.0', '4', '6720'], ["People who grew up in a different socioeconomic class as your significant others, what are the notable differences you've noticed and how does it affect your relationship (if at all)?", '7419', '1440358069.0', '0', '8603'], ['What are the best YouTube channels to binge watch ?', '7311', '1448550352.0', '0', '10306'], ["What website could you recommend that most probably haven't heard of?", '7192', '1436444823.0', '0', '10336'], ['(Serious) At the end of a job interview when they ask me, "So, do you have any questions?", what are some genuinely good questions to ask?', '7133', '1431063658.0', '1', '5850'], ['What do insanely poor people buy, that ordinary people know nothing about?', '6850', '1421181185.0', '2', '21559'], ['Announcing a small contest to promote originality', '6796', '1426377669.0', '1', '1348'], ['What small websites do more people need to be aware of?', '6784', '1423497852.0', '0', '4131'], ['What is that one trick that "they" really don\'t want you to know? [Serious]', '6701', '1444844927.0', '0', '17724'], ["Who is the scariest person you've ever met?", '6689', '1439520757.0', '0', '9234'], ['What was your "I don\'t get paid enough for this shit" moment?', '6596', '1439947180.0', '0', '11815'], ['What gets weirder and weirder the more you think about it?', '6538', '1439545860.0', '1', '12762'], ['[Serious] Redditors who want Trump to become president, why?', '6526', '1439138685.0', '0', '14580'], ["What's your favourite movie that most of us wouldn't have even ever heard of?", '6472', '1439899943.0', '0', '19050'], ['(Serious) People of Reddit who have HIV/AIDS, when did you realize something was wrong?', '6472', '1439213819.0', '0', '4296'], ['What cities ARE worth visiting?', '6451', '1439291187.0', '0', '16953'], ["People who lived in Compton in the mid to late 80's, was it really as it is depicted by N.W.A? What are some crazy things that you witnessed?", '6410', '1440564883.0', '0', '4515'], ['What small websites do you visit?', '6400', '1440020488.0', '1', '4731'], ['[Serious] What are some great apps for smartphones that people might not be aware of?', '6346', '1443887658.0', '0', '7833'], ["What fact or statistic seems like obvious exaggeration, but isn't?", '6320', '1448885731.0', '0', '23159'], ['Reddit, what was your "It\'s totally not a phase, mom/dad!" that ended up being just a phase?', '6271', '1439906197.0', '0', '14115'], ['If your life depended on getting someone to laugh, which youtube video would you show them?', '6267', '1422612478.0', '1', '6023'], ['What are the best text-based subreddits to kill time reading?', '6210', '1445251377.0', '0', '2477'], ['What was the first event that disproved your childhood belief that the world is a safe place?', '6192', '1439642253.0', '0', '10824'], ["What's the cleanest, least offensive, funniest joke you know?", '6162', '1439568880.0', '0', '4692'], ['If you could send an anonymous text to yourself 5 years ago, what would you write?', '6109', '1439985692.0', '0', '13735'], ['Redditors who have met a former crush years later, how did it turn out?', '6110', '1439735429.0', '0', '8530'], ['What are the best computer hackers able to do right now that most people are unaware of?', '6113', '1449128988.0', '0', '8267'], ['What is a short (<1min) video that always cracks you up?', '6073', '1445810268.0', '0', '9164'], ['REMINDER: Only the dark side posts spoilers without a spoiler tag. Please, use the spoiler tag!', '6089', '1450212277.0', '0', '1058'], ['[Serious] people who have twin siblings but are not a twin themselves, how is your relationship with your twin brothers or sisters?', '6050', '1439856706.0', '0', '3110'], ['[serious] Therapists/psychiatrists of reddit: what is something that most people think they are alone in experiencing/feeling/thinking?', '6045', '1447844725.0', '2', '7019'], ['How would you go about making an extra $500 a month (outside of your normal salary)?', '6046', '1441194071.0', '1', '16944'], ['What is the scariest *real* organization in the world?', '6019', '1446583374.0', '1', '14091'], ['What was your biggest "shit, my parents were right" moment?', '6007', '1446384482.0', '0', '18033'], ["Reddit, What lesser known Apps can't you live without?", '5988', '1432728287.0', '2', '13726'], ["[Serious] What's the creepiest TRUE story that happened to you or someone you know?", '5982', '1439744268.0', '0', '8358'], ['How do you subtly fuck with people?', '5978', '1438996121.0', '0', '9304'], ['What is a cool qualification that you can easily get?', '5972', '1431453813.0', '0', '6381'], ["What's considered trashy if you're poor, but classy if you're rich?", '5951', '1443233511.0', '0', '8182'], ['If all of a sudden all humans simultaneously lost the ability to sneeze, how long do you think it would take mankind as a collective to realize?', '5943', '1423787549.0', '7', '4427'], ['Teachers of reddit, what is the greatest way a student has misinterpreted one of your assignments?', '5937', '1447697520.0', '0', '10289'], ["Fathers of Reddit, what did your daughter's boyfriend do for you to hate/love him?", '5924', '1440582629.0', '0', '9878'], ["Redditors who spend a lot of time in seclusion (at sea, in the air or out in the wilderness) what's the creepiest or most mysterious thing you've seen, found or experienced?", '5922', '1444699740.0', '1', '15873'], ['What is the best game to play in a web browser?', '5903', '1429904281.0', '1', '8812'], ['What should not be considered OK, but is often encouraged?', '5878', '1440154625.0', '0', '18115'], ['People who live near famous tourist destinations, what is something the average person should know?', '5867', '1438276265.0', '0', '25806'], ['What is your go-to random fact?', '5860', '1436984888.0', '0', '14637'], ["What's the most calculated thing you've ever seen an animal do?", '5872', '1448910548.0', '1', '8094'], ['How do you subtly fuck with people?', '5829', '1421966837.0', '1', '15419'], ['What mobile app has actually had a legitimate positive impact on your life?', '5831', '1449174161.0', '0', '10961'], ["Commercial airplane pilots, what's the closest disaster you've averted while on a flight that the passengers had no idea about? How often do these things happen?", '5799', '1440418465.0', '0', '4947'], ['What items would be inside a Second Aid Kit?', '5796', '1439338307.0', '0', '2900'], ["What's a short, clean joke that gets a laugh every time?", '5779', '1426597584.0', '2', '12007'], ['Who ruined something as thoroughly as Hitler ruined the toothbrush moustache?', '5783', '1442166787.0', '0', '12134'], ['What movie do you quote/reference the most?', '5767', '1438871651.0', '0', '17507'], ['If Dr. Seuss was a real doctor, what would his diagnoses sound like?', '5767', '1440330433.0', '0', '1658'], ['What food is not as bad for you as most people believe?', '5755', '1439809974.0', '0', '12801'], ["What is the smallest lie you've ever told which had the biggest consequences?", '5750', '1447943291.0', '0', '7011'], ['What was the biggest bluff in history?', '5725', '1435489814.0', '1', '8625'], ['What is never going to stop being funny?', '5733', '1441137267.0', '0', '12692'], ['Parent of a "weird kid", how did you react when you realized that your kid did weird/creepy stuff?', '5720', '1440515374.0', '0', '5997'], ['What piece of stand up comedy (10 minutes or less) has successfully made you cry with laughter?', '5700', '1437140705.0', '0', '5581'], ['What was the worst PR move in history?', '5700', '1436280395.0', '0', '14338'], ['Which song is most improved when all occurrences of "I," "me," "my," etc. are replaced with "Greg"?', '5687', '1444838170.0', '6', '11183'], ["What are common signs of not having one's shit together?", '5687', '1449534179.0', '0', '13807'], ["What's a good date other than dinner and a movie?", '5681', '1450384351.0', '0', '9451'], ['What is a phrase that makes you instantly dislike someone strongly?', '5632', '1439304421.0', '0', '24533'], ['What would be a funny thing to say to a surgeon before anesthesia kicks in 5 seconds later?', '5618', '1444926824.0', '1', '8778'], ['Women who use tinder, what are you actually looking for?', '5602', '1439469826.0', '0', '11618']]
serious_count = 0
for row in posts:
    if re.search("[(\[\()(Ss)]erious[(\)\])]", row[0]) is not None:
        serious_count += 1
serious_count

9

## Sub


### Best way to get rid of punctuation using regexp

In [3]:
import string
print(string.punctuation)

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [6]:
import re
import string
punct = '[{}]'.format(re.escape(string.punctuation))
# return a pattern object
regex = re.compile(punct)
string = " Hello! What a beautiful day, how are you?"
print(regex.sub("", string))

 Hello What a beautiful day how are you


## Get rid of lower alphabetical letters and space:

In [7]:
import re
import string
punct = '[{}]'.format('a-z ')
# return a pattern object
regex = re.compile(punct)
s = " Hello! What a beautiful day, how are you?"
print(regex.sub("", string))

H!W,?


## match
### Select only specific characters:

In [9]:
#!/usr/bin/python
import re

line = "Cats are smarter than dogs"

matchObj = re.match( r'(.*) are (.*?) .*', line, re.M|re.I)
#re.I performs case-insensitive matching.
# re.M Makes $ match the end of a line (not just the end of the string) and 
# makes ^ match the start of any line (not just the start of the string).
if matchObj:
    print("matchObj.group() : ", matchObj.group())
    print("matchObj.group(1) : ", matchObj.group(1))
    print("matchObj.group(2) : ", matchObj.group(2))
else:
    print("No match!!")

matchObj.group() :  Cats are smarter than dogs
matchObj.group(1) :  Cats
matchObj.group(2) :  smarter


**LE code suivant ne marhe pas avec le troisieme argument: re.M ou re.I**

In [9]:
import re
line = "Cats are smarter than dogs"
regex = re.compile(r'(.*) are (.*?) .*')
matchObj = regex.match(line)
if matchObj:
    print("matchObj.group() : ", matchObj.group())
    print("matchObj.group(1) : ", matchObj.group(1))
    print("matchObj.group(2) : ", matchObj.group(2))
else:
    print("No match!!")

matchObj.group() :  Cats are smarter than dogs
matchObj.group(1) :  Cats
matchObj.group(2) :  smarter


## findall

In [2]:
import re
years_string = '2015 was a good year, but 2016 will be better!'
years= re.findall("[1-2][0-9]{3}", years_string)
print(years)

['2015', '2016']


In [11]:
line = " [as(dd)]{asdasd}(asd)"

pattern = re.compile('[\{\(\[\]\)\}]')
final = pattern.findall(line)
opened = ['[', '{', '(']
closed = [']', '}', ')']

print(final)

['[', '(', ')', ']', '{', '}', '(', ')']


CHeck if brackets are properly structured: 
    
    [blah blah]{blah blah} returns True
    ([]{}) returns True
    )][] returns False

In [34]:
line = " [as(dd)]{asdasd}(asd)"

pattern = re.compile('[\{\(\[\]\)\}]')
final = pattern.findall(line)
opened = ['[', '{', '(']
closed = [']', '}', ')']

result = True

while len(final) >= 2 and result:
    i = 0
    while (i < len(final)) and (final[i] in opened):
        last_opened = final[i]
        i += 1

    index_last = opened.index(last_opened)
    if (final[i] == closed[index_last]):
        final.pop(i-1)
        final.pop(i-1)
    else:
        result = False
    print(final)

if len(final) != 0:
    result = False
print(result)
    


2
)
)
['[', '(', ')', ']', '{', '}', '(', ')']
1
i 2
['[', ']', '{', '}', '(', ')']
0
]
]
['[', ']', '{', '}', '(', ')']
0
i 1
['{', '}', '(', ')']
1
}
}
['{', '}', '(', ')']
0
i 1
['(', ')']
2
)
)
['(', ')']
0
i 1
[]
True


### More details

In [18]:
help(re.compile)

Help on function compile in module re:

compile(pattern, flags=0)
    Compile a regular expression pattern, returning a pattern object.



> sub can also be used as a method, pattern objects are the result of compile method: pattern_Object.(replacementForThePattern, stringToBeProcessed): best way for optimising execution time.

> It can also be used as follows but it is slower!

In [20]:
help(re.sub)

Help on function sub in module re:

sub(pattern, repl, string, count=0, flags=0)
    Return the string obtained by replacing the leftmost
    non-overlapping occurrences of the pattern in string by the
    replacement repl.  repl can be either a string or a callable;
    if a string, backslash escapes in it are processed.  If it is
    a callable, it's passed the match object and must return
    a replacement string to be used.



### Other methods to replace punctuation: From Stackoverflow

In [23]:
import re, timeit

s = "string. With. Punctuation"
exclude = set(string.punctuation)
table = str.maketrans("","")
regex = re.compile('[%s]' % re.escape(string.punctuation))

def test_set(s):
    return ''.join(ch for ch in s if ch not in exclude)

def test_re(s):  # From Vinko's solution, with fix.
    return regex.sub('', s)

def test_re2(s):  # From Vinko's solution, with fix.
    return re.sub(r'[%s]' % re.escape(string.punctuation), '', s)

def test_trans(s):
    return s.translate(str.maketrans(dict.fromkeys(string.punctuation)))

def test_repl(s):  # From S.Lott's solution
    for c in string.punctuation:
        s=s.replace(c,"")
    return s

print("regex     :",timeit.Timer('f(s)', 'from __main__ import s,test_re2 as f').timeit(1000000))
print("sets      :",timeit.Timer('f(s)', 'from __main__ import s,test_set as f').timeit(1000000))
print("regex     :",timeit.Timer('f(s)', 'from __main__ import s,test_re as f').timeit(1000000))
print("translate :",timeit.Timer('f(s)', 'from __main__ import s,test_trans as f').timeit(1000000))
print("replace   :",timeit.Timer('f(s)', 'from __main__ import s,test_repl as f').timeit(1000000))

regex     : 11.503616341999077
sets      : 3.43686759800039
regex     : 1.2260810600000696
translate : 5.684141095000086
replace   : 6.976052489999347


## How to print ordinal numbers: first as 1st, second as 2nd

In [73]:
ordinal = lambda n: "{}{}".format(n,"tsnrhtdd"[(n/10%10!=1)*(n%10<4)*n%10::4])
print(ordinal(2))

2nd


### Old formatting way

In [12]:
ordinal = lambda n: "%d%s" % (n,"tsnrhtdd"[(n/10%10!=1)*(n%10<4)*n%10::4])
print(ordinal(3))

3rd


# Pandas
## Iterating over rows in a pandas dataframe:

iterrows is a generator which yield both index and row (as a Series object)

In [7]:
import pandas
import csv

jeopardy = pandas.read_csv("data/jeopardy.csv")
sample = jeopardy.head(2)
for i, row in sample.iterrows():
    print(i)
    print(row)

0
Show Number                                                 4680
 Air Date                                             2004-12-31
 Round                                                 Jeopardy!
 Category                                                HISTORY
 Value                                                      $200
 Question      For the last 8 years of his life, Galileo was ...
 Answer                                               Copernicus
Name: 0, dtype: object
1
Show Number                                                 4680
 Air Date                                             2004-12-31
 Round                                                 Jeopardy!
 Category                        ESPN's TOP 10 ALL-TIME ATHLETES
 Value                                                      $200
 Question      No. 2: 1912 Olympian; football star at Carlisl...
 Answer                                               Jim Thorpe
Name: 1, dtype: object


# math module

In [85]:
import math
ab = 10
bc = 10
# Soit un triangle ABC rectangle en B, calcul de l'angle aCb
angle = math.atan2(bc, ab)
print("{0:d}°".format(round(math.degrees(angle))))

45°


# Numpy
## Matrix product Numpy

`import numpy as np
n = int(input())
a = np.array([input().split() for i in range(n)],dtype=np.int) 
b = np.array([input().split() for i in range(n)],dtype=np.int)
print(np.dot(a,b))`

## Polynomials

The poly tool returns the coefficients of a polynomial with the given sequence of roots.

`print numpy.poly([-1, 1, 1, 10])`        #Output : [  1 -11   9  11 -10]


Given the coefficients of a polynomial P, find th value of P at point x.

The polyval tool evaluates the polynomial at specific value:
`import numpy
print(numpy.polyval(numpy.array(input().split(), float), float(input())))`


The polyfit tool fits a polynomial of a specified order to a set of data using a least-squares approach.

`print numpy.polyfit([0,1,-1, 2, -2], [0,1,1, 4, 4], 2)` #Output : [  1.00000000e+00   0.00000000e+00  -3.97205465e-16]

The roots tool returns the roots of a polynomial with the given coefficients.

`print numpy.roots([1, 0, -1])`           #Output : [-1.  1.]




The polyint tool returns an antiderivative (indefinite integral) of a polynomial.

`print numpy.polyint([1, 1, 1])`         #Output : [ 0.33333333  0.5         1.          0.        ]


polyder

The polyder tool returns the derivative of the specified order of a polynomial.

`print numpy.polyder([1, 1, 1, 1])`      #Output : [3 2 1]


## Linear Algebra

The NumPy module also comes with a number of built-in routines for linear algebra calculations. These can be found in the sub-module linalg.

linalg.det

The linalg.det tool computes the determinant of an array.

`print numpy.linalg.det([[1 , 2], [2, 1]])`       #Output : -3.0


You are given a square matrix with dimensions X. Your task is to find the determinant.

Input Format

The first line contains the integer .
The next lines contains the space separated elements of array .

Output Format

Print the determinant .


`import numpy
n = int(input())
a = numpy.array([input().split() for _ in range(n)], float)
print(numpy.linalg.det(a))`

linalg.eig

The linalg.eig computes the eigenvalues and right eigenvectors of a square array.

`vals, vecs = numpy.linalg.eig([[1 , 2], [2, 1]])`

`print vals`                                      #Output : [ 3. -1.]

`print vecs`                                      #Output : [[ 0.70710678 -0.70710678]
                                                #          [ 0.70710678  0.70710678]]

linalg.inv

The linalg.inv tool computes the (multiplicative) inverse of a matrix.

print numpy.linalg.inv([[1 , 2], [2, 1]])       #Output : [[-0.33333333  0.66666667]
                                                #          [ 0.66666667 -0.33333333]]



## getattr(object, string)

Python’s getattr function is used to fetch an attribute from an object, using a string object instead of an identifier to identify the attribute. 

In [24]:
# value = obj.attribute
obj ='CATS'
value = getattr(obj, "lower")()
print(value)

# value = obj.attribute
obj =['a', 2, 3]
value = getattr(obj, "index")('a')
print(value)

cats
0


If the attribute exists, the corresponding value is returned. If the attribute does not exist, you get an AttributeError exception instead.

# cProfile

In [14]:
import cProfile
 
pr = cProfile.Profile()
pr.enable()
 
# call_function()
 
pr.disable()
 
pr.print_stats(sort='time')

         10 function calls in 0.000 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.compile}
        1    0.000    0.000    0.000    0.000 interactiveshell.py:2851(run_code)
        1    0.000    0.000    0.000    0.000 codeop.py:132(__call__)
        1    0.000    0.000    0.000    0.000 <ipython-input-14-04ff7db62cbe>:8(<module>)
        1    0.000    0.000    0.000    0.000 hooks.py:139(__call__)
        1    0.000    0.000    0.000    0.000 ipstruct.py:125(__getattr__)
        1    0.000    0.000    0.000    0.000 interactiveshell.py:1065(user_global_ns)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
        1    0.000    0.000    0.000    0.000 hooks.py:204(pre_run_code_hook)




In [ ]:
import re
import cProfile
 
pr = cProfile.Profile()
pr.enable()
 
line = " [as(dd)]{asdasd}(asd)"*1000

pattern = re.compile('[\{\(\[\]\)\}]')
final = pattern.findall(line)
opened = ['[', '{', '(']
closed = [']', '}', ')']

pr.disable()
 
pr.print_stats(sort='time')

# numpy random normal

In [ ]:
plt.hist(np.random.normal(0,0.01,size=(100,1)))
plt.show()